#!/bin/bash

# First thing we want to do is to check if our database files exists.
# if not move them from /tmp/ to the shared folder.
#if [ ! -s /u01/app/oracle/oradata/ORCL/apps01.dbf ] && [ ! -s /u01/app/oracle/oradata/ORCL/indx01.dbf ]
#	then
#    mv /tmp/ORCL/* /u01/app/oracle/oradata/ORCL/
#fi

while true; do
  status=`ps -ef | grep tns | grep oracle`
  pmon=`ps -ef | egrep pmon_$ORACLE_SID'\>' | grep -v grep`
  if [ "$status" == "" ] || [ "$pmon" == "" ]
  then
    lsnrctl start
    sqlplus /nolog @?/config/scripts/startdb.sql
    lsnrctl status
  fi
  sleep 1m
done;
