#!/bin/bash

echo "Creating database..."
sqlplus /nolog @?/config/scripts/createdb.sql
echo ""

echo "Creating password file..."
cd $ORACLE_HOME/dbs
$ORACLE_HOME/bin/orapwd FILE=orapw$ORACLE_SID password=change_on_install
echo ""

echo "Running catalog.sql..."
cd $ORACLE_HOME/rdbms/admin
cp catalog.sql catalog-e.sql
echo "exit" >> catalog-e.sql
sqlplus / as sysdba @?/rdbms/admin/catalog-e.sql > /tmp/catalog.log
rm catalog-e.sql
echo ""

echo "Running catproc.sql..."
cd $ORACLE_HOME/rdbms/admin
cp catproc.sql catproc-e.sql
echo "exit" >> catproc-e.sql
sqlplus / as sysdba @?/rdbms/admin/catproc-e.sql > /tmp/catproc.log
rm catproc-e.sql
echo ""

# Product User Profile Build, this is for SQLPlus only (Will give warning message on login if not run)
echo "Running pupbld.sql..."
cd $ORACLE_HOME/sqlplus/admin
cp pupbld.sql pupbld-e.sql
echo "exit" >> pupbld-e.sql
sqlplus system/manager @?/sqlplus/admin/pupbld-e.sql > /tmp/pupbld.log
rm pupbld-e.sql
echo ""

echo "Finalizing install and shutting down the database..."
sqlplus / as sysdba @?/config/scripts/conf_finish.sql
